version: '3.7'

services:
  app:
    build: .
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - elasticsearch
      - logstash

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    tmpfs: [/var/lib/mysql:rw]
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.9.3
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes: [./docker/logstash.conf:/etc/logstash/conf.d/logstash.conf]
    environment: [ELASTICSEARCH_HOST=elasticsearch]

#  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:7.7.1
#    ports: [5601:5601]
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200