version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19

  pre_build:
    commands:
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin

  build:
    commands:
      - docker-compose up -d app

      - docker-compose exec -T app /app/tests/test.sh
